apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
    app: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet 
    spec:
      containers:
      - name: dotnetserver
        image: bitnami/dotnet:latest
        ports:
        - containerPort: 4000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 4000
    nodePort: 41110
